---
- name: Setup Web Server
  hosts: all
  remote_user : root
  become: yes
  become_method: sudo


  tasks:
    - name: Installing properties
      apt:
        name:
          - python3-pip
          - git
          - lsb-release
          - ca-certificates
          - apt-transport-https
          - software-properties-common
          - gnupg2
          - curl
          - wget
          - debconf-utils
          - libaio1
    - name: Install PyMySQL
      shell: python3 -m pip install PyMySQL
    - name: Install Cryptography
      shell: pip install cryptography
    - name: Install Apache
      apt:
        name: apache2, apache2-utils

    - name: Installing PHP and associated modules
      apt:
        name: php8.1, libapache2-mod-php8.1, php8.1-cli, php8.1-common, php8.1-mysql, php8.1-opcache, php8.1-soap, php8.1-zip, php8.1-intl, php8.1-bcmath, php8.1-xml, php8.1-xmlrpc, php8.1-curl, php8.1-gd, php8.1-imagick, php8.1-cli, php8.1-dev, php8.1-imap, php8.1-mbstring
    - name: Mysql
      shell:
        debconf-set-selections <<EOF
        mysql-apt-config mysql-apt-config/select-server select mysql-8.0
        "mysql-community-server mysql-community-server/root-pass password root"
        "mysql-community-server mysql-community-server/re-root-pass password root"
        EOF

    - name: Mysql apt config
      shell: wget --user-agent="Mozilla" -O /tmp/mysql-apt-config_0.8.24-1_all.deb https://dev.mysql.com/get/mysql-apt-config_0.8.24-1_all.deb
    - name: Mysql Apt config
      shell: sudo DEBIAN_FRONTEND=noninteractive dpkg -i /tmp/mysql-apt-config_0.8.24-1_all.deb < /dev/null > /dev/null
    - name: Mysql apt update
      apt:
        update_cache: true
        upgrade: true
    - name: Installing Mysql
      shell: DEBIAN_FRONTEND=noninteractive apt-get install mysql-server mysql-client --assume-yes --force-yes < /dev/null > /dev/null
    - name: Mysql
      shell: 'mysql -ne "{{ item }}"'
      with_items:
        - CREATE DATABASE uthman;
    - name: Creating Database
      shell: 'mysql -ne "{{ item }}"'
      with_items:
        - CREATE USER 'uthman'@'localhost' IDENTIFIED BY 'uthman';
    - name: Granting privileges
      shell: 'mysql -ne "{{ item }}"'
      with_items:
        - GRANT ALL PRIVILEGES ON uthman.* TO 'uthman'@'localhost';
    - name: mysql setup
      shell: 'mysql -ne "{{ item }}"'
      with_items:
        - FLUSH PRIVILEGES;
    - name: Flushing privileges
      copy:
        src: /home/vagrant/pgsql.sh
        dest: /root
    - name: pgsql
      shell: bash /root/pgsql.sh
    - name: Cloning laravel app
      shell: git clone https://github.com/f1amy/laravel-realworld-example-app.git /var/www/laravel
    - name: Installing laravel
      copy:
        dest: /var/www/laravel/.env
        content: |
          APP_NAME="Laravel"
          APP_ENV=local
          APP_KEY=
          APP_DEBUG=true
          APP_URL=https://localhost
          APP_PORT=3000
          LOG_CHANNEL=stack
          LOG_DEPRECATIONS_CHANNEL=null
          LOG_LEVEL=debug
          DB_CONNECTION=mysql
          DB_HOST=localhost
          DB_PORT=3306
          DB_DATABASE=laravel
          DB_USERNAME=laravel
          DB_PASSWORD=laravel
          BROADCAST_DRIVER=log
          CACHE_DRIVER=file
          FILESYSTEM_DISK=local
          QUEUE_CONNECTION=sync
          SESSION_DRIVER=file
          SESSION_LIFETIME=120
          MEMCACHED_HOST=127.0.0.1
          REDIS_HOST=127.0.0.1
          REDIS_PASSWORD=null
          REDIS_PORT=6379
          MAIL_MAILER=smtp
          MAIL_HOST=mailhog
          MAIL_PORT=1025
          MAIL_USERNAME=null
          MAIL_PASSWORD=null
          MAIL_ENCRYPTION=null
          MAIL_FROM_ADDRESS="hello@example.com"
          MAIL_FROM_NAME="${APP_NAME}"
          AWS_ACCESS_KEY_ID=
          AWS_SECRET_ACCESS_KEY=
          AWS_DEFAULT_REGION=us-east-1
          AWS_BUCKET=
          AWS_USE_PATH_STYLE_ENDPOINT=false
          PUSHER_APP_ID=
          PUSHER_APP_KEY=
          PUSHER_APP_SECRET=
          PUSHER_APP_CLUSTER=mt1
          MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
          MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
          L5_SWAGGER_GENERATE_ALWAYS=true
          SAIL_XDEBUG_MODE=develop,debug
          SAIL_SKIP_CHECKS=true
    - name: Laravel
      blockinfile:
        path: /var/www/laravel/routes/web.php
        block: |
          Route::get('/', function () {
            return view('welcome');
          });
    - name: Laravel permission
      shell: chown -R root:root /var/www/laravel
    - name: Laravel permission
      shell: chmod -R 0755 /var/www/laravel
    - name: Laravel permission
      shell: chmod -R 0755 /var/www/laravel/storage
    - name: Laravel permission
      shell: chmod -R 0755 /var/www/laravel/bootstrap/cache
    - name: Laravel
      copy:
        dest: "/var/www/laravel/.htaccess"
        content: |
          <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteCond %{REQUEST_URI} !^/public/
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^(.*)$ /public/$1
            RewriteRule ^(/)?$ public/index.php [L]
          </IfModule>

    - name: Download composer
      shell: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - name: Installing composer
      shell: php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - name: Installing composer setup
      shell: php composer-setup.php
    - name: Composer
      shell: php -r "unlink('composer-setup.php');"
    - name: moving composer file
      shell: mv composer.phar /usr/local/bin/composer
    - name: Creating a project
      shell: cd /var/www/laravel && composer create-project -n
    - name: Artisan migration
      shell: cd /var/www/laravel && php artisan migrate --seed

    - name: Modifying .conf file
      copy:
        dest: "/etc/apache2/sites-available/officespacecalifornia.conf"
        content: |
          <VirtualHost *:80>
              ServerAdmin email@newmexicoautorepair.com
              ServerName newmexicoautorepair.com
              ServerAlias newmexicoautorepair.com
              DocumentRoot /var/www/laravel/public
              <Directory /var/www/laravel/public>
                  Options Indexes FollowSymLinks
                  AllowOverride All
                  Require all granted
              </Directory>
              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>


    - name: enable a2dissite
      shell: a2dissite 000-default.conf
    - name: enable a2ensite
      shell: a2ensite officespacecalifornia.conf
    - name: enable a2enmod rewrite
      shell: a2enmod rewrite
    - name: restart apache2
      service:
        name: apache2
        state: restarted
    

    - name: granting permission
      shell: chown -R www-data:www-data /var/www/laravel
    - name: Core
      apt:
        name:
          - snapd
    - name: snap install core
      shell: snap install core
    - name: refresh core
      shell: snap refresh core
    - name: install classic certbot
      shell: snap install --classic certbot
    - name: install
     shell: ln -s /snap/bin/certbot /usr/bin/certbot
    - name: Redirect
      shell: yes | certbot --apache --agree-tos --redirect -m email@newmexicoautorepair.com -d newmexicoautorepair.com

